function EvDa(E){function c(a,b,f){if(!a)return{data:d,setters:l,events:h};if(c.isPaused)w.push(["invoke",arguments]);else{if(k(a)){var g=q.call(arguments,1);return F(a,function(a){return c.apply(c.context,[a].concat(g))})}if(1==arguments.length){if(x(a)){var r={};e(a,function(a,b){r[a]=c(a,b,f,0,1)});e(r,function(b,c){n(r[b])&&!n(a[b])&&(a[b]=r[b]())});return a}return d[a]}return c[n(b)?v:"set"].apply(this,arguments)}}function y(a){e(a.$,function(b){h[b]=C(h[b],a)})}function p(a,b,f){if(k(a)){var g=
a.pop();return p(g,function(c,f){return p(1==a.length?a[0]:a,b,f)},f)}if(x(a))return e(a,function(b,c){a[b]=p(b,c,f)}),a;l[a]&&(l[a](function(b){c.set.call(c.context,a,b,f)}),delete l[a]);return b?a in d?b.call(c.context,d[a],f):c(a,b,s(f||{},D)):a in d}var q=Array.prototype.slice,z=Object.prototype.toString,k=[].isArray||function(a){return"[object Array]"===z.call(a)},n=function(a){return!!(a&&a.constructor&&a.call&&a.apply)},A=function(a){return!!(""===a||a&&a.charCodeAt&&a.substr)},x=function(a){return A(a)?
!1:null==a?"object"==String(a):"[object Object]"===z.call(a)||!0},e=[].forEach?function(a,b){if(k(a)||a.length)q.call(a).forEach(b);else for(var c in a)b(c,a[c])}:function(a,b){if(k(a))for(var c=0,g=a.length;c<g;c++)b(a[c],c);else for(c in a)b(c,a[c])},B={}.keys||function(a){if(k(a))return a;var b=[],c;for(c in a)b.push(c);return b},C=function(a,b){var c=[];e(a,function(a){a!==b&&c.push(a)});return c},G=function(a){var b,c=[];e(B(a).sort(),function(a){a!=b&&(b=a,c.push(a))});return c},H=function(a,
b){var c=[];e(a,function(a){b(a)&&c.push(a)});return c},u=function(a){return a&&"length"in a?a.length:0},F=[].map?function(a,b){return a.map(b)}:function(a,b){for(var c=[],g=0,d=a.length;g<d;g++)c.push(b(a[g],g));return c},I=function(a){return k(a)?q.call(a):x(a)?s(a,{}):a},s=function(a){e(q.call(arguments,1),function(b){for(var c in b)void 0!==b[c]&&(a[c]=b[c])});return a},v="on",D={once:1},d=E||{},w=[],l={},h={};e([v,"after","test","or"],function(a){c[a]=function(b,c,g){c||(c=b,b="__base");(c.$||
(c.$=[])).push(a+b);(h[a+b]||(h[a+b]=[])).push(c);return s(c,g)}});s(c,{_:{},context:this,list:{},isPaused:!1,db:d,setterMap:l,events:h,del:y,whenSet:p,invoke:c,isset:p,pause:function(){c.isPaused||(c.isPaused=!0,c._.set=c.set,c.set=function(){w.push(["set",arguments])})},play:function(){c.isPaused=!1;var a=EvDa();c.set=c._.set;e(w,function(b){a[b[0]].apply(a,b[1])});c(a.db)},setter:function(a,b){l[a]=b;if(h[v+a])return p(a)},when:function(a,b,f){if(A(b))try{var g=new Function("x","return x"+b);g();
b=g}catch(d){}return c(a,function(a){(k(b)&&b.sort().join("")===a.sort().join("")||n(b)&&b(a)||a===b)&&f.call(c.context,a)})},incr:function(a,b){b=b||1;return c.set(a,"[object Number]"===z.call(d[a])?d[a]+b:b)},decr:function(a,b){return c.set(a,d[a]-(b||1)||0)},push:function(a,b){1==u(arguments)&&(b=a,a="__base");return c.set(a,[].concat(d[a]||[],[b]))},pop:function(a){return c.set(a||"__base",d[a].slice(0,-1))},traceList:[],group:function(a){var b=q.call(arguments);a=b.shift();b=c.apply(0,b);c.list[a]||
(c.list[a]=[]);n(b)?c.list[a].push(b):e(b,function(b,d){c.list[a].push(b)});return function(){return c.group.apply(0,[a].concat(q.call(arguments)))}},set:function(a,b,f,g,r){var m="test"+a,k=q.call(arguments),l=u(h[m]),p=l&&!g,n,t=p?function(d){n|=!1===d;--l||(n?e(h["or"+a]||[],function(a){a.S||(a.call(c.context,b,f),a.once&&y(a))}):c.set(a,b,f,1))}:{};t.old=I(d[a]);s(t,{meta:f||{},done:t,result:t,key:a});if(p)e(h[m],function(a){a.call(c.context,b,t)});else return e(c.traceList,function(a){a.call(c.context,
k)}),d[a]=b,m=function(){e((h[v+a]||[]).concat(h["after"+a]||[]),function(a){a.S||(a.call(c.context,b,t),a.once&&y(a))});return b},r?m:m.call(c.context);return d[a]},once:function(a,b,f){return b?c.once(c(a,b,f)):s(a,D)},enable:function(a){e(c.list[a],function(b){b.S&&b.S[a]&&delete b.S[a];0==u(b.S)&&delete b.S});return c.list[a]},setadd:function(a,b){return c(a,G((d[a]||[]).concat([b])))},setdel:function(a,b){return c(a,C(d[a]||[],b))},disable:function(a){e(c.list[a],function(b){(b.S||(b.S={}))[a]=
!0});return c.list[a]},unset:function(){var a=!0;e(arguments,function(b){a&=b in d;delete d[b]});return a},find:function(a){return H(B(d),function(b){return b.match(a)})},changed:function(a,b){b||(b=a,a="__base");return c.on(a,function(a,d){var e=u(a),m=u(d.old);1==e-m?b.call(c.context,a.length?a[a.length-1]:void 0):e>m&&b.call(c.context,q.call(a).slice(m))})},sniff:function(){var a={},b=+new Date,d=function(c){a[c[0]]||console.log(+new Date-b,c)},e=function(){},h=d;c.traceList.unshift(function(a){h(a)});
c.sniff=function(b){if(0<arguments.length){if(A(b))return a[b]=!a[b],"[Un]ignoring "+b;h=b?d:e;return b}return B(a)}}});c.setAdd=c.setadd;c.setDel=c.setdel;c.isSet=c.isset;c.get=c;c.change=c.on;c.add=c.push;c.isArray=k;return c};
